name: Build Unsigned iOS IPA

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: List files
        run: |
          ls -la
          ls -la MPVKit || true
          cat .gitmodules || true

      - name: Build iOS without signing
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build
